export const SEARCHED_TERM = "SEARCHED_TERM";
export const FETCH_CLIENT_IP = "FETCH_CLIENT_IP";
export const FETCH_SEARCHED_IP = "FETCH_SEARCHED_IP";
export const FETCH_SEARCHED_ERROR_TRUE = "FETCH_SEARCHED_ERROR_TRUE";
export const FETCH_SEARCHED_ERROR_FALSE = "FETCH_SEARCHED_ERROR_FALSE";
